### ISSUE TITLE
D435 on Gazebo

### ISSUE THREAD

**Issue by nuitvolgit** [NMBURobotics/botanbot_sim#1]
Hello, 
I appreciate your grrat work work!
I am trying to use d435 in Gazebo but
there was no plugin in the model.sdf file.
I googled it but couldn't find.
Could you please add d435 plugin to your model?
Thanks!

**Comment by jediofgever** [comment]
Hi,
Thanks for your interest. This project is only to simulate a robot model itself but not sensors.
You might have a look at project in below link. It’s a set of sensor plugin for gazebo composed as one gazebo model. So you can attach this model which is named “sensor suite” to your robot model, it includes realsense and some other sensors. 
https://github.com/NMBURobotics/ros2_full_sensor_suite

**Comment by nuitvolgit** [comment]
Thank you for the info! I will try them out.
