### ISSUE TITLE
botanbot.urdf camera related joint problem

### ISSUE THREAD

**Issue by nuitvolgit** [NMBURobotics/botanbot_sim#2]
Hello, 
I was struggling to change all the camera related link positions in the botanbot.urdf 
No matter how I change the joint position in the urdf, all cameras were located to the base link.

It turned out that the poses of the camera related joints in the botanbot.urdf file must be changed from 
<pose .... /> to <origin .../>

For example, 
from
```
<joint name="camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_bottom_screw_frame" />
        <pose xyz="0.3 0.0 0.8" rpy="0 0 0" />
    </joint>
```

to 
```
<joint name="camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_bottom_screw_frame" />
        <origin xyz="0.3 0.0 0.8" rpy="0 0 0" />
    </joint>
```

Please check this out.
Thanks.

**Comment by jediofgever** [comment]
Hi,

Thank you for the feedback. I will have a look into this in some time.
