### ISSUE TITLE
The left and right rear wheels have different friction ode (mu, mu2) in the model.sdf

### ISSUE THREAD

**Issue by nuitvolgit** [NMBURobotics/botanbot_sim#3]
Hello, 

The left and right rear wheels have different friction ode (mu, mu2) in the model.sdf
This caused different left and right rotation charecteristics in the simulation.
Please check it out. 

Thanks.

**Comment by jediofgever** [comment]
Hi 
Many thanks for the reporting back ! 

Would also be very appreciated if you open a PR with the fix

**Comment by nuitvolgit** [comment]
I would like to modify from 'This caused... ' to 'This might cause ...'.
It would't effect as seriously as I expected.

**Comment by jediofgever** [comment]
The friction parameters were changed because it was causing robot to slip while encountering hilll or slope
