### ISSUE TITLE
Models missing on launch

### ISSUE THREAD

**Issue by AddyPete** [NMBURobotics/botanbot_sim#9]
Hello i got this error when i tried to launch. It seems it can't load the models mentioned.
**Start Selected Gazebo World Standalone**  I choosed city_world as the world.

This is the error message in terminal

```
[gazebo-1] [Wrn] [ModelDatabase.cc:340] Getting models from[http://models.gazebosim.org/]. This may take a few seconds.
[gazebo-1] [Wrn] [SystemPaths.cc:459] File or path does not exist [""] [model://botanbot]
[gazebo-1] [Wrn] [SystemPaths.cc:459] File or path does not exist [""] [model://vrc_heightmap_1]
```

The core part of the botanbot model is missing as you can see below

![Screenshot from 2023-10-16 15-16-04](https://github.com/NMBURobotics/botanbot_sim/assets/40378950/607996be-1601-4091-a3e3-982aeafa5337)

**Comment by jediofgever** [comment]
Looks like you need to append the gazebo model path to include models in botanbot_gazebo package. 

export GAZEBO_MODEL_PATH=[...]/models:$GAZEBO_MODEL_PATH

Add this to your ~/.bashrc file.

replace the […] with absolute path to models folder in botanbot_gazebo package

**Comment by AddyPete** [comment]
thank you for this. it works now
